services:
  expo:
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./food:/app/food  # monta a pasta do projeto no container
    stdin_open: true
    tty: true
