version: "3.8"

services:
  expo:
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: sh -c "npx create-expo-app food || true && cd food && npx expo start --tunnel"
